#!/usr/bin/env python
configfile = "dataFlowCopy.conf"

import sys, os, socket, signal

from configobj import ConfigObj
from Logging import getLogger
import cmsDataFlowCopy

log = getLogger()

def getMergeParams(copyConfigFileName):
    try:
        if os.path.isfile(copyConfigFileName):
            config = ConfigObj(copyConfigFileName)
        else:
            log.error("Configuration file not found: {0}!".format(copyConfigFileName))
            sys.exit(1)
    except IOError, e:
        log.error("Unable to open configuration file: {0}!".format(copyConfigFileName))
        sys.exit(1)

    return config

def get_params():
    params = getMergeParams(configfile)

    try:
        in_path = params['Input']['dataPath']
        out_path = params['Output']['dataPath']
        eol_path = params['Input']['eolPath']
    except KeyError, e:
        log.error("At least one non-optional parameter missing from the config file {0}:".format(configFile))
        log.error("{0}".format(e))
        exit(1)

    try:
        delete_files = params['Misc']['deleteFiles']
    except KeyError, e:
        delete_files = "True"

    try:
        debug_level = params['Misc']['debugLevel']
    except KeyError, e:
        debug_level = 10

    return in_path, eol_path, out_path, delete_files, debug_level


def DataFlowCopy():


  [inPath, eolPath, outPath, delOrigFiles, debugLevel] = get_params()

  log.info("delFiles: {0}".format(delOrigFiles))

  cmsDataFlowCopy.start_copying(inPath, eolPath, outPath, delOrigFiles, debugLevel)

if __name__ == "__main__":

    DataFlowCopy()
